In [1]:
import numpy as np

# AND 게이트(no activation)

In [2]:
def AND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([.5, .5])
    b = 0.7
    temp = np.sum(x * w) - 0.7
    if temp <= 0:
        return 0
    else:
        return 1

In [3]:
AND(0, 0)   # -0.7

0

In [4]:
AND(0, 1)   # -0.2

0

In [5]:
AND(1, 0)   # -0.2

0

In [6]:
AND(1, 1)   # 0.3

1

# NAND 게이트(no activation)

In [7]:
def NAND(x1, x2):
    x = np.array([x1, x2])
    w = np.array([-.5, -.5])
    b = .7
    temp = np.sum(x * w) + b
    if temp <= 0:
        return 0
    else:
        return 1

In [8]:
NAND(0, 0)   # 0.7

1

In [9]:
NAND(0, 1)   # 0.2

1

In [10]:
NAND(1, 0)   # 0.2

1

In [11]:
NAND(1, 1)   # -0.3

0

# OR 게이트(no activation)

In [12]:
def OR(x1, x2):
  x = np.array([x1, x2])
  w = np.array([.5, .5])
  b = -.2
  temp = np.sum(w*x) + b
  if temp <=0:
      return 0
  else:
      return 1

In [13]:
OR(0, 0)

0

In [14]:
OR(1, 0)

1

In [15]:
OR(0, 1)

1

In [16]:
OR(1, 1)

1

# XOR 게이트(no activation)

In [17]:
def XOR(x1, x2):
    s1 = NAND(x1, x2)   # (1, 1)을 제외하고 모두
    s2 = OR(x1, x2)    # (0, 0)을 제외하고 모두
    y = AND(s1, s2)   # -> (0, 1), (1, 0)
    return y

In [18]:
XOR(0, 0)

0

In [19]:
XOR(1, 0)

1

In [20]:
XOR(0, 1)

1

In [21]:
XOR(1, 1)

0

# Activation Function

## step_function

In [22]:
def step_function(x):   # x가 scala인 경우
    if x > 0:
        return 1
    else:
        return 0

In [23]:
x = 2.3
step_function(x)

1

In [24]:
def step_function(x):   # x가 행렬인 경우
    y = x > 0
    return y.astype(np.int)   # True -> 1, False -> 0으로 변경

In [25]:
x = np.array([-1., 1., 2.])
step_function(x)

array([0, 1, 1])

## sigmoid

In [26]:
def sigmoid(x):
    return np.exp(x) / (np.exp(x) + 1)    # return 1 / (1 + np.exp(-x))

In [27]:
x = np.array([-1., 1., 2.])
sigmoid(x)

array([0.26894142, 0.73105858, 0.88079708])

## relu

In [28]:
def relu(x):
    return np.maximum(0, x)

In [29]:
x = np.array([-1., 1., 2.])
relu(x)

array([0., 1., 2.])

## Softmax

In [30]:
def softmax(a):
    exp_a = np.exp(a)
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [31]:
a = np.array([1, 2, 3])
softmax(a)

array([0.09003057, 0.24472847, 0.66524096])

In [32]:
a = np.array([710, 800, 2010, 400, 500, 902, 703])   # 너무 큰 값들에 대해서는 계산이 불가
softmax(a)

<ipython-input-30-37433be62e67>:2: RuntimeWarning: overflow encountered in exp
  exp_a = np.exp(a)
<ipython-input-30-37433be62e67>:4: RuntimeWarning: invalid value encountered in true_divide
  y = exp_a / sum_exp_a


array([nan, nan, nan,  0.,  0., nan,  0.])

In [33]:
def softmax(a):
    c = np.max(a)
    exp_a = np.exp(a - c)    # 최대값을 빼줌으로써 정규화시킴
    sum_exp_a = np.sum(exp_a)
    y = exp_a / sum_exp_a
    return y

In [34]:
a = np.array([710, 800, 2010, 400, 500, 902, 703])
softmax(a)

array([0., 0., 1., 0., 0., 0., 0.])

# Neural Network

In [35]:
def init_network():
    network = {}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([0.1, 0.2, 0.3])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([0.1, 0.2])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([0.1, 0.2])
    return network

In [36]:
def forward(network, x):
    W1, W2, W3 = network['W1'], network['W2'], network['W3']
    b1, b2, b3 = network['b1'], network['b2'], network['b3']

    # np.dot() : 행렬곱
    a1 = np.dot(x, W1) + b1   # 1x2 \dot 2x3  + 1X3 -> 1X3   
    z1 = sigmoid(a1)
    print("z1 = sigmoid(np.dot(x, W1) + b1)=", z1)
    a2 = np.dot(z1, W2) + b2   # 1x3 \dot 3x2  + 1X2 -> 1X2
    z2 = sigmoid(a2)
    print("z2 = sigmoid(np.dot(z1, W2) + b2)=", z2)
    a3 = np.dot(z2, W3) + b3   # 1x2 \dot 2x2  + 1X2 -> 1X2
    y = softmax(a3)
    print("y = sigmoid(np.dot(z2, W3) + b3)=", y)

    return y

In [37]:
network = init_network()
x = np.array([1.0, 0.5])
y = forward(network, x)
y

z1 = sigmoid(np.dot(x, W1) + b1)= [0.57444252 0.66818777 0.75026011]
z2 = sigmoid(np.dot(z1, W2) + b2)= [0.62624937 0.7710107 ]
y = sigmoid(np.dot(z2, W3) + b3)= [0.40625907 0.59374093]


array([0.40625907, 0.59374093])