## 1. tf.Variable vs tf.Constant

In [1]:
import tensorflow as tf

tensorflow의 구성요소 : datasets -> model(weight, bias) -> loss  
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<-  optimizer  <-

=> datasets는 수정이 불가능하게, immutable하게 생성되는게 맞고  
&nbsp;&nbsp;&nbsp;model의 weight와 bias는 수정 가능하게, mutable하게 생성되어야 한다  
=> 따라서 2가지 종류의 텐서가 필요하다!

In [2]:
t1 = tf.Variable([1, 2, 3])
t2 = tf.constant([1, 2, 3])
print(t1)
print(t2)

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
tf.Tensor([1 2 3], shape=(3,), dtype=int32)


In [3]:
print(type(t1))
print(type(t2))

<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


Tensorflow안에서 흐르는 객체들은 tf에서 정의한 Tensor로 되어있는데,  
이는 tf.Variable과 tf.constant로 구분된다

## 2. Tensor의 변환

가장 많이 쓰이는 자료형 : python의 list,  numpy의 ndarray  
=> 둘다 모두 tf.tensor로 바꿀 수 있다!

In [6]:
import numpy as np

test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

t1 = tf.constant(test_list)
t2 = tf.constant(test_np)

print(t1)
print(t2)

print(type(t1))
print(type(t2))

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int64)
<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [7]:
test_list = [1, 2, 3]
test_np = np.array([1, 2, 3])

t1 = tf.Variable(test_list)
t2 = tf.Variable(test_np)

print(t1)
print(t2)

print(type(t1))
print(type(t2))

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>
<tf.Variable 'Variable:0' shape=(3,) dtype=int64, numpy=array([1, 2, 3])>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
<class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>


In [8]:
t1 = tf.constant(test_list)
t2 = tf.Variable(test_list)

# t3 = tf.constant(t2)  => 에러 발생 
t4 = tf.Variable(t1)
# Variable->constant로의 변환은 불가능, constant->Variable 변환은 가능

In [13]:
t1 = tf.convert_to_tensor(test_list)
t2 = tf.convert_to_tensor(test_np)

print("type(t1): ", type(t1))
print("type(t2): ", type(t2))

t3 = tf.Variable(test_list)
t4 = tf.convert_to_tensor(t3)   # 이렇게 하면 Variable -> Constant로의 변환이 가능!

print("type(t3): ", type(t3))
print("type(t4): ", type(t4))

type(t1):  <class 'tensorflow.python.framework.ops.EagerTensor'>
type(t2):  <class 'tensorflow.python.framework.ops.EagerTensor'>
type(t3):  <class 'tensorflow.python.ops.resource_variable_ops.ResourceVariable'>
type(t4):  <class 'tensorflow.python.framework.ops.EagerTensor'>


=> convert_to_tensor는 기본적으로 EagerTensor, 즉 constant Tensor로 변환시키고,  
=> convert_to_tensor를 이용하면 variable Tensor를 constant Tensor로 변환시키는 것도 가능하다

## 3. Tensor의 연산

In [14]:
test_list1 = [10, 20, 30]
test_list2 = [1, 2, 3]

t1 = tf.constant(test_list1)
t2 = tf.constant(test_list2)

t3 = t1 + t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [15]:
t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [16]:
t1 = tf.constant(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>


In [17]:
t1 = tf.Variable(test_list1)
t2 = tf.Variable(test_list2)

t3 = t1 + t2
print(type(t3))

<class 'tensorflow.python.framework.ops.EagerTensor'>


=> (constant, constant), (constant, Variable), (Variable, Variable)에서  
&nbsp;&nbsp;&nbsp;연산 결과는 모두 EagerTensor이다.