In [3]:
import tensorflow as tf
import tensorflow_datasets as tfds
import numpy as np

In [4]:
train_x = np.arange(100).reshape(-1, 1)
train_y = 3*train_x + 1

train_validation_ds = tf.data.Dataset.from_tensor_slices((train_x, train_y))

## 1. Dataset의 take(), skip()을 이용해서 데이터 분할하기

In [6]:
tmp_ds = train_validation_ds.take(5)  # 5개를 뽑아서 새로운 Dataset 만듦
for x, y in tmp_ds:
    print(x)
    print(y, '\n')

tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64) 

tf.Tensor([1], shape=(1,), dtype=int64)
tf.Tensor([4], shape=(1,), dtype=int64) 

tf.Tensor([2], shape=(1,), dtype=int64)
tf.Tensor([7], shape=(1,), dtype=int64) 

tf.Tensor([3], shape=(1,), dtype=int64)
tf.Tensor([10], shape=(1,), dtype=int64) 

tf.Tensor([4], shape=(1,), dtype=int64)
tf.Tensor([13], shape=(1,), dtype=int64) 



In [18]:
# 80%의 데이터셋을 학습데이터로 사용
n_train_validation = 100
train_ratio = 0.8
n_train = int(n_train_validation * train_ratio)
n_validation = n_train_validation - n_train

print(n_train)
print(n_validation)

80
20


In [19]:
# Dataset.skip() 알아보기
remaining_ds = train_validation_ds.skip(n_train)  # 앞에서 10개를 건너뛰고 dataset을 만들 수 있음

for x, y in remaining_ds:
    print(x)
    print(y, '\n')
    break

tf.Tensor([80], shape=(1,), dtype=int64)
tf.Tensor([241], shape=(1,), dtype=int64) 



In [21]:
# 데이터 분할
train_ds = train_validation_ds.take(n_train)
validation_ds = remaining_ds.take(n_validation)

In [22]:
# train_ds, validation_ds의 첫번째 데이터 확인해보기
for x, y in train_ds:
    print(x)
    print(y, '\n')
    break

print()

for x, y in validation_ds:
    print(x)
    print(y, '\n')
    break

tf.Tensor([0], shape=(1,), dtype=int64)
tf.Tensor([1], shape=(1,), dtype=int64) 


tf.Tensor([80], shape=(1,), dtype=int64)
tf.Tensor([241], shape=(1,), dtype=int64) 



## 2. mnist 데이터셋에 적용

In [28]:
(train_validation_ds, test_ds), ds_info = tfds.load(name='mnist',
                                                    shuffle_files=True,
                                                    as_supervised=True,
                                                    split=['train', 'test'],
                                                    with_info=True)

print(ds_info.splits)
print('[\'train\'].num_examples: ', ds_info.splits['train'].num_examples)

{'test': <tfds.core.SplitInfo num_examples=10000>, 'train': <tfds.core.SplitInfo num_examples=60000>}
['train'].num_examples:  60000


In [32]:
n_train_validation = ds_info.splits['train'].num_examples
train_ratio = 0.8
n_train = int(n_train_validation * train_ratio)
n_validation = n_train_validation - n_train

In [34]:
# take(), skip()을 이용한 데이터 분할
train_ds = train_validation_ds.take(n_train)
remaining_ds = train_validation_ds.skip(n_train)
validation_ds = remaining_ds.take(n_validation)

In [35]:
# 데이터 전처리(shuffle, batch)
train_ds = train_ds.shuffle(100).batch(32)
validation_ds = validation_ds.batch(32)
test_ds = test_ds.batch(32)