In [1]:
import tensorflow as tf
import numpy as np

## 1. 사칙 연산

In [2]:
t1 = tf.constant([1, 2, 3])
t2 = tf.constant([10, 20, 30])

print(t1 + t2)   # elementwise 하게 더해짐

tf.Tensor([11 22 33], shape=(3,), dtype=int32)


In [3]:
python_list1 = [1, 2, 3]
python_list2 = [10, 20, 30]

print(python_list1 + python_list2)  # 마치 방명록처럼 concatanate됨

[1, 2, 3, 10, 20, 30]


In [4]:
print(t1 + t2)
print(t1 - t2)
print(t1 * t2)
print(t1 / t2)
print(t1 % t2)
print(t1 // t2)

tf.Tensor([11 22 33], shape=(3,), dtype=int32)
tf.Tensor([ -9 -18 -27], shape=(3,), dtype=int32)
tf.Tensor([10 40 90], shape=(3,), dtype=int32)
tf.Tensor([0.1 0.1 0.1], shape=(3,), dtype=float64)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([0 0 0], shape=(3,), dtype=int32)


## 3. Broadcasting

In [6]:
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)

t1 = tf.cast(t1, dtype=tf.int16)
t2 = tf.cast(t2, dtype=tf.int16)

print(t1.numpy())
print(t2.numpy())

[[ 5 -2 -2 -1]
 [-5 -2  6 -3]
 [-3  4  5  0]]
[[ 3 -1 -1 -5]
 [-1 10  1 -4]
 [ 9  0  1 -4]]


In [7]:
print(t1 + t2)

tf.Tensor(
[[ 8 -3 -3 -6]
 [-6  8  7 -7]
 [ 6  4  6 -4]], shape=(3, 4), dtype=int16)


In [9]:
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t2 = tf.random.normal(shape=(1, 4), mean=0, stddev=5)
t3 = t1 + t2

print(t1.numpy(), '\n')
print(t2.numpy(), '\n')
print(t3.numpy(), '\n')

[[-4.726514   -8.33371    12.880049    0.10143455]
 [-7.1678967   7.34418     2.3417494  -2.5567772 ]
 [-4.476263   -1.6258138  -4.4601483  -0.19648042]] 

[[ 1.539767    0.97189075 -3.2783484  -6.2078247 ]] 

[[-3.1867468 -7.361819   9.6017    -6.10639  ]
 [-5.62813    8.316071  -0.936599  -8.764602 ]
 [-2.936496  -0.6539231 -7.738497  -6.404305 ]] 



In [10]:
t1 = tf.random.normal(shape=(3, 1), mean=0, stddev=5)
t2 = tf.random.normal(shape=(1, 4), mean=0, stddev=5)
t3 = t1 + t2

print(t1.numpy(), '\n')
print(t2.numpy(), '\n')
print(t3.numpy(), '\n')

[[-1.85452 ]
 [-3.231297]
 [ 4.209206]] 

[[ 0.90211844  2.9417002  -4.933199   -4.4259005 ]] 

[[-0.9524015   1.0871803  -6.787719   -6.2804203 ]
 [-2.3291786  -0.2895968  -8.164495   -7.6571975 ]
 [ 5.1113243   7.1509066  -0.7239928  -0.21669436]] 



## 3. 행/열 연산 함수

*  tf.reduce_sum  /  tf.reduce_prod
*  tf.reduce_max  /  tf.reduce_min  
*  tf.reduce_mean  /  tf.reduce_std  / tf.reduce_variance  
*  tf.reduce_all  /  tf.reduce_any  


In [12]:
t1 = tf.random.normal(shape=(3, 4), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

In [17]:
t2 = tf.reduce_sum(t1)
print(t1.numpy(), '\n')
print(t2.numpy())

[[  7   3  -2   6]
 [ -8  -1 -11   2]
 [  9  12   4   0]] 

21


In [16]:
# low-wise/column-wise 연산
t2 = tf.reduce_sum(t1, axis=0)
print(t1.numpy(), '\n')
print(t2.numpy())

[[  7   3  -2   6]
 [ -8  -1 -11   2]
 [  9  12   4   0]] 

[ 8 14 -9  8]


axis=0은 0번째 축, 즉 행을 없애면서 더하라는 뜻이다

In [18]:
t2 = tf.reduce_sum(t1, axis=1)
print(t1.numpy(), '\n')
print(t2.numpy())

[[  7   3  -2   6]
 [ -8  -1 -11   2]
 [  9  12   4   0]] 

[ 14 -18  25]


### 다차원 배열에의 적용

In [20]:
t1 = tf.random.normal(shape=(128, 128, 3), mean=0, stddev=5)
t1 = tf.cast(t1, dtype=tf.int16)

t2 = tf.reduce_sum(t1, axis=2)  # channel-wise로 sum을 구해라
print(t1.shape, '\n')
print(t2.shape)

(128, 128, 3) 

(128, 128)


In [22]:
t2 = tf.reduce_mean(t1, axis=2)  # channel-wise로 mean을 구해라
print(t1.shape, '\n')
print(t2.shape)

(128, 128, 3) 

(128, 128)
